name: Generate Snake Animation

on:
  # Chạy tự động mỗi ngày vào 0h UTC (7h sáng Việt Nam)
  schedule:
    - cron: "0 0 * * *"
  # Cho phép chạy thủ công
  workflow_dispatch:

# Cấp quyền ghi cho GitHub Actions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake game from contributions
        uses: Platane/snk@v3
        with:
          github_user_name: Quanhpm
          outputs: dist/snake.svg

      - name: Push generated snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
